const Color = {
  white: 'white',
  black: 'black',
  blue: 'blue',
  transparent: 'transparent',
  grey: 'grey',
  priceBlue: '#4b9ea5',
  red: 'red',
  backgroundRed: '#FEE3ED',
  textRed: '#DBA3AE',
  textGrey: '#DBDBDB',
  buttonBlue: '#00A9B6',
  tabBlue: '#03A8B3',
  tabGrey: '#DCDCDC',
  lightGrey: '#FAFAFA',
  lightlightGrey: '#EFF1F1',
  lightGreenishBlue: '#01CCB0',
  shadyGreenishBlue: '#DDF5F4',
}
export default Color
